name = "api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-10-23"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1
